package com.arjunren.banking.service;

import com.arjunren.banking.domain.*; import com.arjunren.banking.dto.Dtos.*; import com.arjunren.banking.entity.*; import com.arjunren.banking.exception.DomainException; import com.arjunren.banking.repository.*;
import java.math.*; import java.util.UUID;
import org.springframework.data.domain.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;

@Service
public class BankingService {
    private final BankAccountRepository accounts; private final AccountTransactionRepository transactions;
    public BankingService(BankAccountRepository accounts,AccountTransactionRepository transactions){this.accounts=accounts;this.transactions=transactions;}
    @Transactional(readOnly=true) public PageResponse<AccountResponse> accounts(AppUser actor,int page,int size){Page<BankAccount> p=actor.getRole()==Role.ADMIN?accounts.findAll(PageRequest.of(page,size,Sort.by("id"))):accounts.findByOwnerId(actor.getId(),PageRequest.of(page,size,Sort.by("id")));return new PageResponse<>(p.map(AccountResponse::of).getContent(),page,size,p.getTotalElements(),p.getTotalPages());}
    @Transactional(readOnly=true) public AccountResponse account(Long id,AppUser actor){return AccountResponse.of(owned(accounts.findById(id).orElseThrow(()->notFound("Account not found")),actor));}
    @Transactional public AccountResponse deposit(Long id,BigDecimal amount,String description,AppUser actor){var a=owned(active(lock(id)),actor);a.credit(money(amount));transactions.save(new AccountTransaction(a,TransactionType.DEPOSIT,money(amount),reference(),description,actor));return AccountResponse.of(a);}
    @Transactional public AccountResponse withdraw(Long id,BigDecimal amount,String description,AppUser actor){var a=owned(active(lock(id)),actor);BigDecimal value=money(amount);if(a.getBalance().compareTo(value)<0)throw new DomainException(HttpStatus.CONFLICT,"Insufficient funds");a.debit(value);transactions.save(new AccountTransaction(a,TransactionType.WITHDRAWAL,value,reference(),description,actor));return AccountResponse.of(a);}
    @Transactional public void transfer(TransferRequest r,AppUser actor){if(r.fromAccountId().equals(r.toAccountId()))throw new DomainException(HttpStatus.UNPROCESSABLE_ENTITY,"Source and destination accounts must differ");long first=Math.min(r.fromAccountId(),r.toAccountId()),second=Math.max(r.fromAccountId(),r.toAccountId());var one=lock(first);var two=lock(second);var from=r.fromAccountId().equals(one.getId())?one:two;var to=r.toAccountId().equals(one.getId())?one:two;owned(active(from),actor);active(to);var value=money(r.amount());if(from.getBalance().compareTo(value)<0)throw new DomainException(HttpStatus.CONFLICT,"Insufficient funds");from.debit(value);to.credit(value);String ref=reference();transactions.save(new AccountTransaction(from,TransactionType.TRANSFER_OUT,value,ref,r.description(),actor));transactions.save(new AccountTransaction(to,TransactionType.TRANSFER_IN,value,ref,r.description(),actor));}
    @Transactional(readOnly=true) public PageResponse<TransactionResponse> history(Long id,AppUser actor,int page,int size){owned(accounts.findById(id).orElseThrow(()->notFound("Account not found")),actor);var p=transactions.findByAccountId(id,PageRequest.of(page,size,Sort.by(Sort.Direction.DESC,"createdAt")));return new PageResponse<>(p.map(TransactionResponse::of).getContent(),page,size,p.getTotalElements(),p.getTotalPages());}
    private BankAccount lock(Long id){return accounts.findByIdForUpdate(id).orElseThrow(()->notFound("Account not found"));} private BankAccount active(BankAccount a){if(a.getStatus()!=AccountStatus.ACTIVE)throw new DomainException(HttpStatus.CONFLICT,"Account is not active");return a;} private BankAccount owned(BankAccount a,AppUser u){if(u.getRole()!=Role.ADMIN&&!a.getOwner().getId().equals(u.getId()))throw new DomainException(HttpStatus.FORBIDDEN,"Cannot access another customer's account");return a;} private BigDecimal money(BigDecimal v){return v.setScale(2,RoundingMode.UNNECESSARY);} private String reference(){return UUID.randomUUID().toString();} private DomainException notFound(String m){return new DomainException(HttpStatus.NOT_FOUND,m);}
}

